---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fiph-os
description: Personal OS image. Based on aurora-dx with some minor adjustments

base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable-daily

modules:
  - type: dnf
    repos:
      files:
        - https://download.opensuse.org/repositories/home:paulmcauley/Fedora_%OS_VERSION%/home:paulmcauley.repo
      copr:
        - deltacopy/darkly
      cleanup: true
    install:
      packages:
        - klassy
        - darkly
    remove:
      packages:
        - tailscale
  - type: script
    scripts:
      - panel-colorizer.sh
      - kwin_geometry.sh
    secrets:
      - type: env
        name: GITHUB_TOKEN
        mount:
          type: env
          name: GITHUB_TOKEN
  - type: signing
