---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fiph-os
description: Personal OS image. Based on aurora-dx with some minor adjustments

base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable-daily

modules:
  - type: dnf
    repos:
      copr:
        - varlad/zellij
        - errornointernet/klassy
        - deltacopy/darkly
    install:
      packages:
        - zellij
        - klassy
        - darkly
    remove:
      packages:
        - tailscale
  - type: script
    scripts:
      - plasma.sh

  - type: signing