---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fiph-os
description: Personal OS image. Based on aurora-dx with some minor adjustments

base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - varlad/zellij
        - errornointernet/klassy
    install:
      packages:
        - zellij
        - klassy
    remove:
      packages:
        - tailscale

  - type: signing